name: brick_breaker
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5
  google_fonts: ^6.3.0
  shared_preferences: ^2.5.3
  flame: ^1.32.0
  flame_forge2d: ^0.19.2
  flame_audio: ^2.11.10
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/profile_images/gabriel.png
    - assets/profile_images/helena.png
    - assets/profile_images/joao.png
    - assets/profile_images/julio.png
    - assets/profile_images/lucas.png
    - assets/profile_images/tiago.png
    - assets/audio/brick.mp3
    - assets/audio/game_over.mp3
    - assets/audio/level_beat.mp3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/bricks.png"
